name: 'Mark stale issues and PRs'

on:
  schedule:
    - cron: '0 1 * * *' # Runs at 1 AM UTC every day

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity.'
          stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity.'
          days-before-stale: 60
          days-before-close: 7
